version: 0.0
os: linux

files:
  - source: /
    destination: /root

hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: fix_privileges.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: server_start.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 30
      runas: root