version: 0.0
os: linux

files:
  - source: /java-maven-app-2.2.19.jar
    destination: /opt/

hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
    - location: server_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: root