version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
    - echo Nothing to do with the install phase...
  pre_build:
    commands:
    - echo Nothing to do with the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - mvn clean install
  post_build:
    commands:
    - echo Build completed on `date`
    - cp scripts/*.sh .
    - cp target/*.jar .
    - tar -czf myapp.tgz fix_privileges.sh server_clear.sh server_start.sh server_stop.sh java-maven-app-2.2.19.jar
artifacts:
  files:
  - myapp.tgz
  
