version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
    - echo Nothing to do with the install phase...
  pre_build:
    commands:
    - echo Nothing to do with the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - mvn clean install
  post_build:
    commands:
    - echo Build completed on `date`
    - aws deploy push --application-name myapp-1 --s3-location s3://myapp-3889/helloworld.zip --ignore-hidden-files --region us-east-1
    

